# frozen_string_literal: true
source 'https://supermarket.chef.io'

cookbook 'apt'
cookbook 'system'
cookbook 'build-essential'
cookbook 'ruby_build'
cookbook 'ruby_rbenv'
cookbook 'postgresql'
cookbook 'nodejs'

metadata
