name 'lxd_web_interface'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures lxd_web_interface'
long_description 'Installs/Configures lxd_web_interface'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)

depends 'apt'
depends 'system'
depends 'build-essential'
depends 'ruby_rbenv'
depends 'postgresql'
depends 'nodejs'
